layout_spectrum: 0.06611473264467746
typography_spectrum: 0.21503560454160492
color:
  brandColors:
    - '#354242'
    - '#ACEBAE'
    - '#FFFF9D'
    - '#C9DE55'
    - '#7D9100'
  brandStrength: 0.8890645147916298
  lightness: 0.9343586156040541
  saturation: 0.3288920404438372
  rhythmicContrast: 0.5748211972450487
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Zack Exley
  email: me@zackexley.com
  url: zackexley.com
name: Zack Exley
url: 'http://zackexley.com'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Yours
content: []
description: for the revolution
purpose: []
