layout_spectrum: 0.76256539968368
typography_spectrum: 0.14158348840449264
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.6798217373026886
  lightness: 0.7402612387761474
  saturation: 0.869754920039455
  rhythmicContrast: 0.19255235961158898
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Zack Exley
  email: me@zackexley.com
  url: zackexley.com
name: Zack Exley
url: 'http://zackexley.com'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Yours
content: []
description: for the revolution
purpose: []
