typography_spectrum: 0.2144871595259387
color:
  brandColors:
    - '#354242'
    - '#ACEBAE'
    - '#FFFF9D'
    - '#C9DE55'
    - '#7D9100'
  brandStrength: 0.2739363619156809
  lightness: 0.20254361761392714
  saturation: 0.9004063973060376
  rhythmicContrast: 0.02719827632327555
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.33794239969011214
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Zack Exley
  email: me@zackexley.com
  url: zackexley.com
name: Zack Exley
url: 'http://zackexley.com'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Yours
content: []
description: for the revolution
purpose: []
